#define SONAR_TRIG_PIN A0 // analog input 1
#define SONAR_ECHO_PIN A1 // analog input 2

#define LEFT_MOTOR_BACKWARD_PIN 10
#define LEFT_MOTOR_FORWARD_PIN 9
#define RIGHT_MOTOR_BACKWARD_PIN 11
#define RIGHT_MOTOR_FORWARD_PIN 12

#define RIGHT_LED_RED_PIN 6
#define RIGHT_LED_GREEN_PIN 7
//#define RIGHT_LED_BLUE_PIN 8

#define LEFT_LED_RED_PIN 4
#define LEFT_LED_GREEN_PIN 5
//#define LEFT_LED_BLUE_PIN 11

#define SERVO_MOTOR_PIN 8