#define SONAR_TRIG_PIN A0 // analog input 1
#define SONAR_ECHO_PIN A1 // analog input 2

#define LEFT_MOTOR_BACKWARD_PIN 2
#define LEFT_MOTOR_FORWARD_PIN 3
#define RIGHT_MOTOR_BACKWARD_PIN 4
#define RIGHT_MOTOR_FORWARD_PIN 5

#define RIGHT_LED_RED_PIN 6
#define RIGHT_LED_GREEN_PIN 7
#define RIGHT_LED_BLUE_PIN 8

#define LEFT_LED_RED_PIN 9
#define LEFT_LED_GREEN_PIN 10
#define LEFT_LED_BLUE_PIN 11

#define SERVO_MOTOR_PIN 12